spring.application.name=TaskSphere
spring.config.import=optional:file:.env[.properties]

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/tasksphere}
spring.data.mongodb.database=${MONGODB_DATABASE:tasksphere}

# JWT
app.jwt.secret=TaskSphereJWTSuperSecretKey2024XYZ_MustBe256BitsLong!!
app.jwt.expiration=86400000

# Server
server.port=8090
